/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Customer Data API
 * OpenAPI spec version: 1.0.0
 */
export type GetCustomers200Item = {
  month?: string;
  newCustomers?: number;
  upCrossSelling?: number;
};
