/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */
export type GetApiSalesRevenue200Item = {
  date: string;
  id: number;
  newCustomers: number;
  upCrossSelling: number;
};

export type GetApiProducts200Item = {
  category: string;
  id: number;
  imageUrl: string;
  leaderboardPosition: number;
  purchasesQuantity: number;
  title: string;
};

export type TodaysStatsResponseSales = {
  /** Label for sales */
  label: string;
  /** Sales value */
  value: number;
};

export type TodaysStatsResponseProfit = {
  /** Label for profit */
  label: string;
  /** Profit value */
  value: number;
};

export type TodaysStatsResponseCost = {
  /** Label for cost */
  label: string;
  /** Cost value */
  value: number;
};

export interface TodaysStatsResponse {
  cost: TodaysStatsResponseCost;
  profit: TodaysStatsResponseProfit;
  sales: TodaysStatsResponseSales;
}

export interface AuthResponseDto {
  token?: string;
}

export interface LoginRequestDto {
  email: string;
  password: string;
}

export interface UserDto {
  avatar: string;
  email: string;
  id: string;
  name: string;
}
